[2019-12-12 02:01:54,340] INFO [GroupMetadataManager brokerId=0] Removed 0 expired offsets in 1 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
[2019-12-12 02:11:54,340] INFO [GroupMetadataManager brokerId=0] Removed 0 expired offsets in 1 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
[2019-12-12 02:16:11,982] INFO [GroupCoordinator 0]: Member consumer-2-5611e120-c69c-42aa-a2a2-ef8bc7381f43 in group group_json has left, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2019-12-12 02:16:11,983] INFO [GroupCoordinator 0]: Member consumer-4-bfa31bc9-0c6e-44b0-a2aa-2a514eee4c75 in group group_json_fitness has left, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2019-12-12 02:16:12,039] INFO [GroupCoordinator 0]: Preparing to rebalance group group_json in state PreparingRebalance with old generation 29 (__consumer_offsets-2) (reason: removing member consumer-2-5611e120-c69c-42aa-a2a2-ef8bc7381f43 on LeaveGroup) (kafka.coordinator.group.GroupCoordinator)
[2019-12-12 02:16:12,039] INFO [GroupCoordinator 0]: Group group_json with generation 30 is now empty (__consumer_offsets-2) (kafka.coordinator.group.GroupCoordinator)
[2019-12-12 02:16:12,039] INFO [GroupCoordinator 0]: Preparing to rebalance group group_json_fitness in state PreparingRebalance with old generation 15 (__consumer_offsets-49) (reason: removing member consumer-4-bfa31bc9-0c6e-44b0-a2aa-2a514eee4c75 on LeaveGroup) (kafka.coordinator.group.GroupCoordinator)
[2019-12-12 02:16:12,040] INFO [GroupCoordinator 0]: Group group_json_fitness with generation 16 is now empty (__consumer_offsets-49) (kafka.coordinator.group.GroupCoordinator)
[2019-12-12 02:16:20,030] INFO [GroupCoordinator 0]: Preparing to rebalance group group_json in state PreparingRebalance with old generation 30 (__consumer_offsets-2) (reason: Adding new member consumer-2-96976340-ef2a-4eb7-a0e3-692c8b46ab7f with group instanceid None) (kafka.coordinator.group.GroupCoordinator)
[2019-12-12 02:16:20,031] INFO [GroupCoordinator 0]: Stabilized group group_json generation 31 (__consumer_offsets-2) (kafka.coordinator.group.GroupCoordinator)
[2019-12-12 02:16:20,048] INFO [GroupCoordinator 0]: Assignment received from leader for group group_json for generation 31 (kafka.coordinator.group.GroupCoordinator)
[2019-12-12 02:16:20,065] INFO [GroupCoordinator 0]: Preparing to rebalance group group_json_fitness in state PreparingRebalance with old generation 16 (__consumer_offsets-49) (reason: Adding new member consumer-4-8d2187af-1a4d-438a-978a-19825b6b9c2a with group instanceid None) (kafka.coordinator.group.GroupCoordinator)
[2019-12-12 02:16:20,066] INFO [GroupCoordinator 0]: Stabilized group group_json_fitness generation 17 (__consumer_offsets-49) (kafka.coordinator.group.GroupCoordinator)
[2019-12-12 02:16:20,067] INFO [GroupCoordinator 0]: Assignment received from leader for group group_json_fitness for generation 17 (kafka.coordinator.group.GroupCoordinator)
[2019-12-12 02:21:54,339] INFO [GroupMetadataManager brokerId=0] Removed 0 expired offsets in 0 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
[2019-12-12 02:22:23,168] INFO [Log partition=Fitnessdetails-0, dir=/tmp/kafka-logs] Found deletable segments with base offsets [7] due to retention time 10000ms breach (kafka.log.Log)
[2019-12-12 02:22:23,187] INFO [ProducerStateManager partition=Fitnessdetails-0] Writing producer snapshot at offset 9 (kafka.log.ProducerStateManager)
[2019-12-12 02:22:23,187] INFO [Log partition=Fitnessdetails-0, dir=/tmp/kafka-logs] Rolled new log segment at offset 9 in 1 ms. (kafka.log.Log)
[2019-12-12 02:22:23,187] INFO [Log partition=Fitnessdetails-0, dir=/tmp/kafka-logs] Scheduling log segment [baseOffset 7, size 276] for deletion. (kafka.log.Log)
[2019-12-12 02:22:23,188] INFO [Log partition=Fitnessdetails-0, dir=/tmp/kafka-logs] Incrementing log start offset to 9 (kafka.log.Log)
[2019-12-12 02:23:23,188] INFO [Log partition=Fitnessdetails-0, dir=/tmp/kafka-logs] Deleting segment 7 (kafka.log.Log)
[2019-12-12 02:23:23,291] INFO Deleted log /tmp/kafka-logs/Fitnessdetails-0/00000000000000000007.log.deleted. (kafka.log.LogSegment)
[2019-12-12 02:23:23,292] INFO Deleted offset index /tmp/kafka-logs/Fitnessdetails-0/00000000000000000007.index.deleted. (kafka.log.LogSegment)
[2019-12-12 02:23:23,292] INFO Deleted time index /tmp/kafka-logs/Fitnessdetails-0/00000000000000000007.timeindex.deleted. (kafka.log.LogSegment)
[2019-12-12 02:31:54,340] INFO [GroupMetadataManager brokerId=0] Removed 0 expired offsets in 1 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
[2019-12-12 02:41:22,377] INFO [GroupCoordinator 0]: Member consumer-4-8d2187af-1a4d-438a-978a-19825b6b9c2a in group group_json_fitness has left, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2019-12-12 02:41:22,377] INFO [GroupCoordinator 0]: Member consumer-2-96976340-ef2a-4eb7-a0e3-692c8b46ab7f in group group_json has left, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2019-12-12 02:41:22,377] INFO [GroupCoordinator 0]: Preparing to rebalance group group_json_fitness in state PreparingRebalance with old generation 17 (__consumer_offsets-49) (reason: removing member consumer-4-8d2187af-1a4d-438a-978a-19825b6b9c2a on LeaveGroup) (kafka.coordinator.group.GroupCoordinator)
[2019-12-12 02:41:22,377] INFO [GroupCoordinator 0]: Preparing to rebalance group group_json in state PreparingRebalance with old generation 31 (__consumer_offsets-2) (reason: removing member consumer-2-96976340-ef2a-4eb7-a0e3-692c8b46ab7f on LeaveGroup) (kafka.coordinator.group.GroupCoordinator)
[2019-12-12 02:41:22,377] INFO [GroupCoordinator 0]: Group group_json_fitness with generation 18 is now empty (__consumer_offsets-49) (kafka.coordinator.group.GroupCoordinator)
[2019-12-12 02:41:22,377] INFO [GroupCoordinator 0]: Group group_json with generation 32 is now empty (__consumer_offsets-2) (kafka.coordinator.group.GroupCoordinator)
[2019-12-12 02:41:47,546] INFO [GroupCoordinator 0]: Preparing to rebalance group group_json in state PreparingRebalance with old generation 32 (__consumer_offsets-2) (reason: Adding new member consumer-2-a548a28e-b926-4bcf-9fc3-b81a45414cb1 with group instanceid None) (kafka.coordinator.group.GroupCoordinator)
[2019-12-12 02:41:47,568] INFO [GroupCoordinator 0]: Stabilized group group_json generation 33 (__consumer_offsets-2) (kafka.coordinator.group.GroupCoordinator)
[2019-12-12 02:41:47,579] INFO [GroupCoordinator 0]: Assignment received from leader for group group_json for generation 33 (kafka.coordinator.group.GroupCoordinator)
[2019-12-12 02:41:47,591] INFO [GroupCoordinator 0]: Preparing to rebalance group group_json_fitness in state PreparingRebalance with old generation 18 (__consumer_offsets-49) (reason: Adding new member consumer-4-27b95204-642b-4ef2-9131-58fd6fb9d004 with group instanceid None) (kafka.coordinator.group.GroupCoordinator)
[2019-12-12 02:41:47,613] INFO [GroupCoordinator 0]: Stabilized group group_json_fitness generation 19 (__consumer_offsets-49) (kafka.coordinator.group.GroupCoordinator)
[2019-12-12 02:41:47,616] INFO [GroupCoordinator 0]: Assignment received from leader for group group_json_fitness for generation 19 (kafka.coordinator.group.GroupCoordinator)
[2019-12-12 02:41:54,340] INFO [GroupMetadataManager brokerId=0] Removed 0 expired offsets in 1 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
[2019-12-12 02:45:21,579] INFO [GroupCoordinator 0]: Member consumer-4-27b95204-642b-4ef2-9131-58fd6fb9d004 in group group_json_fitness has left, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2019-12-12 02:45:21,580] INFO [GroupCoordinator 0]: Preparing to rebalance group group_json_fitness in state PreparingRebalance with old generation 19 (__consumer_offsets-49) (reason: removing member consumer-4-27b95204-642b-4ef2-9131-58fd6fb9d004 on LeaveGroup) (kafka.coordinator.group.GroupCoordinator)
[2019-12-12 02:45:21,580] INFO [GroupCoordinator 0]: Group group_json_fitness with generation 20 is now empty (__consumer_offsets-49) (kafka.coordinator.group.GroupCoordinator)
[2019-12-12 02:45:21,579] INFO [GroupCoordinator 0]: Member consumer-2-a548a28e-b926-4bcf-9fc3-b81a45414cb1 in group group_json has left, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2019-12-12 02:45:21,580] INFO [GroupCoordinator 0]: Preparing to rebalance group group_json in state PreparingRebalance with old generation 33 (__consumer_offsets-2) (reason: removing member consumer-2-a548a28e-b926-4bcf-9fc3-b81a45414cb1 on LeaveGroup) (kafka.coordinator.group.GroupCoordinator)
[2019-12-12 02:45:21,580] INFO [GroupCoordinator 0]: Group group_json with generation 34 is now empty (__consumer_offsets-2) (kafka.coordinator.group.GroupCoordinator)
[2019-12-12 02:45:29,152] INFO [GroupCoordinator 0]: Preparing to rebalance group group_json in state PreparingRebalance with old generation 34 (__consumer_offsets-2) (reason: Adding new member consumer-2-7e713011-62d4-472b-8d26-bf80d26edc1e with group instanceid None) (kafka.coordinator.group.GroupCoordinator)
[2019-12-12 02:45:29,174] INFO [GroupCoordinator 0]: Preparing to rebalance group group_json_fitness in state PreparingRebalance with old generation 20 (__consumer_offsets-49) (reason: Adding new member consumer-4-7870fdc9-3b1a-46a0-9cd6-2fc229e7ba85 with group instanceid None) (kafka.coordinator.group.GroupCoordinator)
[2019-12-12 02:45:29,174] INFO [GroupCoordinator 0]: Stabilized group group_json generation 35 (__consumer_offsets-2) (kafka.coordinator.group.GroupCoordinator)
[2019-12-12 02:45:29,178] INFO [GroupCoordinator 0]: Assignment received from leader for group group_json for generation 35 (kafka.coordinator.group.GroupCoordinator)
[2019-12-12 02:45:29,178] INFO [GroupCoordinator 0]: Stabilized group group_json_fitness generation 21 (__consumer_offsets-49) (kafka.coordinator.group.GroupCoordinator)
[2019-12-12 02:45:29,184] INFO [GroupCoordinator 0]: Assignment received from leader for group group_json_fitness for generation 21 (kafka.coordinator.group.GroupCoordinator)
[2019-12-12 02:47:23,168] INFO [Log partition=Fitnessdetails-0, dir=/tmp/kafka-logs] Found deletable segments with base offsets [9] due to retention time 10000ms breach (kafka.log.Log)
[2019-12-12 02:47:23,194] INFO [ProducerStateManager partition=Fitnessdetails-0] Writing producer snapshot at offset 12 (kafka.log.ProducerStateManager)
[2019-12-12 02:47:23,195] INFO [Log partition=Fitnessdetails-0, dir=/tmp/kafka-logs] Rolled new log segment at offset 12 in 26 ms. (kafka.log.Log)
[2019-12-12 02:47:23,195] INFO [Log partition=Fitnessdetails-0, dir=/tmp/kafka-logs] Scheduling log segment [baseOffset 9, size 419] for deletion. (kafka.log.Log)
[2019-12-12 02:47:23,195] INFO [Log partition=Fitnessdetails-0, dir=/tmp/kafka-logs] Incrementing log start offset to 12 (kafka.log.Log)
[2019-12-12 02:48:23,195] INFO [Log partition=Fitnessdetails-0, dir=/tmp/kafka-logs] Deleting segment 9 (kafka.log.Log)
[2019-12-12 02:48:23,436] INFO Deleted log /tmp/kafka-logs/Fitnessdetails-0/00000000000000000009.log.deleted. (kafka.log.LogSegment)
[2019-12-12 02:48:23,436] INFO Deleted offset index /tmp/kafka-logs/Fitnessdetails-0/00000000000000000009.index.deleted. (kafka.log.LogSegment)
[2019-12-12 02:48:23,436] INFO Deleted time index /tmp/kafka-logs/Fitnessdetails-0/00000000000000000009.timeindex.deleted. (kafka.log.LogSegment)
[2019-12-12 02:49:13,021] INFO [GroupCoordinator 0]: Member consumer-4-7870fdc9-3b1a-46a0-9cd6-2fc229e7ba85 in group group_json_fitness has left, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2019-12-12 02:49:13,021] INFO [GroupCoordinator 0]: Preparing to rebalance group group_json_fitness in state PreparingRebalance with old generation 21 (__consumer_offsets-49) (reason: removing member consumer-4-7870fdc9-3b1a-46a0-9cd6-2fc229e7ba85 on LeaveGroup) (kafka.coordinator.group.GroupCoordinator)
[2019-12-12 02:49:13,022] INFO [GroupCoordinator 0]: Group group_json_fitness with generation 22 is now empty (__consumer_offsets-49) (kafka.coordinator.group.GroupCoordinator)
[2019-12-12 02:49:13,021] INFO [GroupCoordinator 0]: Member consumer-2-7e713011-62d4-472b-8d26-bf80d26edc1e in group group_json has left, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2019-12-12 02:49:13,023] INFO [GroupCoordinator 0]: Preparing to rebalance group group_json in state PreparingRebalance with old generation 35 (__consumer_offsets-2) (reason: removing member consumer-2-7e713011-62d4-472b-8d26-bf80d26edc1e on LeaveGroup) (kafka.coordinator.group.GroupCoordinator)
[2019-12-12 02:49:13,023] INFO [GroupCoordinator 0]: Group group_json with generation 36 is now empty (__consumer_offsets-2) (kafka.coordinator.group.GroupCoordinator)
[2019-12-12 02:49:20,980] INFO [GroupCoordinator 0]: Preparing to rebalance group group_json in state PreparingRebalance with old generation 36 (__consumer_offsets-2) (reason: Adding new member consumer-2-b672e943-db3e-419b-a4f7-946d6377064d with group instanceid None) (kafka.coordinator.group.GroupCoordinator)
[2019-12-12 02:49:20,982] INFO [GroupCoordinator 0]: Stabilized group group_json generation 37 (__consumer_offsets-2) (kafka.coordinator.group.GroupCoordinator)
[2019-12-12 02:49:20,985] INFO [GroupCoordinator 0]: Assignment received from leader for group group_json for generation 37 (kafka.coordinator.group.GroupCoordinator)
[2019-12-12 02:49:21,041] INFO [GroupCoordinator 0]: Preparing to rebalance group group_json_fitness in state PreparingRebalance with old generation 22 (__consumer_offsets-49) (reason: Adding new member consumer-4-899a56ef-aed8-41a3-bdd8-e52042be2aaa with group instanceid None) (kafka.coordinator.group.GroupCoordinator)
[2019-12-12 02:49:21,042] INFO [GroupCoordinator 0]: Stabilized group group_json_fitness generation 23 (__consumer_offsets-49) (kafka.coordinator.group.GroupCoordinator)
[2019-12-12 02:49:21,044] INFO [GroupCoordinator 0]: Assignment received from leader for group group_json_fitness for generation 23 (kafka.coordinator.group.GroupCoordinator)
[2019-12-12 02:50:19,712] INFO [GroupCoordinator 0]: Member consumer-2-b672e943-db3e-419b-a4f7-946d6377064d in group group_json has left, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2019-12-12 02:50:19,713] INFO [GroupCoordinator 0]: Preparing to rebalance group group_json in state PreparingRebalance with old generation 37 (__consumer_offsets-2) (reason: removing member consumer-2-b672e943-db3e-419b-a4f7-946d6377064d on LeaveGroup) (kafka.coordinator.group.GroupCoordinator)
[2019-12-12 02:50:19,713] INFO [GroupCoordinator 0]: Group group_json with generation 38 is now empty (__consumer_offsets-2) (kafka.coordinator.group.GroupCoordinator)
[2019-12-12 02:50:19,715] INFO [GroupCoordinator 0]: Member consumer-4-899a56ef-aed8-41a3-bdd8-e52042be2aaa in group group_json_fitness has left, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2019-12-12 02:50:19,716] INFO [GroupCoordinator 0]: Preparing to rebalance group group_json_fitness in state PreparingRebalance with old generation 23 (__consumer_offsets-49) (reason: removing member consumer-4-899a56ef-aed8-41a3-bdd8-e52042be2aaa on LeaveGroup) (kafka.coordinator.group.GroupCoordinator)
[2019-12-12 02:50:19,716] INFO [GroupCoordinator 0]: Group group_json_fitness with generation 24 is now empty (__consumer_offsets-49) (kafka.coordinator.group.GroupCoordinator)
[2019-12-12 02:50:59,734] WARN Client session timed out, have not heard from server in 4410ms for sessionid 0x1000046c90c0000 (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:50:59,888] INFO Client session timed out, have not heard from server in 4410ms for sessionid 0x1000046c90c0000, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:51:02,158] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:51:02,213] INFO Socket connection established to localhost/127.0.0.1:2181, initiating session (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:51:02,653] INFO Session establishment complete on server localhost/127.0.0.1:2181, sessionid = 0x1000046c90c0000, negotiated timeout = 6000 (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:52:09,120] INFO [GroupMetadataManager brokerId=0] Removed 0 expired offsets in 1 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
[2019-12-12 02:52:37,948] INFO [Log partition=Fitnessdetails-0, dir=/tmp/kafka-logs] Found deletable segments with base offsets [12] due to retention time 10000ms breach (kafka.log.Log)
[2019-12-12 02:52:37,949] INFO [ProducerStateManager partition=Fitnessdetails-0] Writing producer snapshot at offset 16 (kafka.log.ProducerStateManager)
[2019-12-12 02:52:37,951] INFO [Log partition=Fitnessdetails-0, dir=/tmp/kafka-logs] Rolled new log segment at offset 16 in 3 ms. (kafka.log.Log)
[2019-12-12 02:52:37,951] INFO [Log partition=Fitnessdetails-0, dir=/tmp/kafka-logs] Scheduling log segment [baseOffset 12, size 354] for deletion. (kafka.log.Log)
[2019-12-12 02:52:37,952] INFO [Log partition=Fitnessdetails-0, dir=/tmp/kafka-logs] Incrementing log start offset to 16 (kafka.log.Log)
[2019-12-12 02:53:37,952] INFO [Log partition=Fitnessdetails-0, dir=/tmp/kafka-logs] Deleting segment 12 (kafka.log.Log)
[2019-12-12 02:53:38,024] INFO Deleted log /tmp/kafka-logs/Fitnessdetails-0/00000000000000000012.log.deleted. (kafka.log.LogSegment)
[2019-12-12 02:53:38,024] INFO Deleted offset index /tmp/kafka-logs/Fitnessdetails-0/00000000000000000012.index.deleted. (kafka.log.LogSegment)
[2019-12-12 02:53:38,024] INFO Deleted time index /tmp/kafka-logs/Fitnessdetails-0/00000000000000000012.timeindex.deleted. (kafka.log.LogSegment)
[2019-12-12 02:56:51,274] INFO Terminating process due to signal SIGHUP (org.apache.kafka.common.utils.LoggingSignalHandler)
[2019-12-12 02:56:51,275] INFO Terminating process due to signal SIGHUP (org.apache.kafka.common.utils.LoggingSignalHandler)
[2019-12-12 02:56:51,429] INFO [KafkaServer id=0] shutting down (kafka.server.KafkaServer)
[2019-12-12 02:56:51,430] INFO [KafkaServer id=0] Starting controlled shutdown (kafka.server.KafkaServer)
[2019-12-12 02:56:51,727] WARN Session 0x1000046c90c0000 for server localhost/127.0.0.1:2181, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.io.IOException: Connection reset by peer
	at java.base/sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:233)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223)
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:358)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:68)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:366)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2019-12-12 02:56:51,862] INFO [ZooKeeperClient Kafka server] Waiting until connected. (kafka.zookeeper.ZooKeeperClient)
[2019-12-12 02:56:51,862] INFO [ZooKeeperClient Kafka server] Connected. (kafka.zookeeper.ZooKeeperClient)
[2019-12-12 02:56:53,799] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:56:53,909] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:56:54,029] INFO [ZooKeeperClient Kafka server] Waiting until connected. (kafka.zookeeper.ZooKeeperClient)
[2019-12-12 02:56:55,630] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:56:55,630] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:56:56,887] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:56:56,888] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:56:58,143] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:56:58,143] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:56:59,644] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:56:59,645] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:57:01,060] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:57:01,061] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:57:02,801] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:57:02,802] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:57:04,411] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:57:04,412] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:57:05,603] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:57:05,604] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:57:07,378] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:57:07,379] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:57:09,026] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:57:09,027] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:57:10,549] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:57:10,549] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:57:12,624] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:57:12,625] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:57:13,867] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:57:13,868] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:57:15,881] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:57:15,882] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:57:17,175] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:57:17,176] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:57:18,893] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:57:18,894] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:57:20,379] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:57:20,380] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:57:21,926] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:57:21,927] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:57:23,284] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:57:23,285] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:57:24,752] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:57:24,753] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:57:26,205] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:57:26,206] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:57:28,178] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:57:28,180] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:57:29,536] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:57:29,537] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:57:31,257] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:57:31,258] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:57:32,375] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:57:32,376] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:57:34,281] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:57:34,282] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:57:36,293] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:57:36,295] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:57:37,410] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:57:37,411] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:57:39,386] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:57:39,387] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:57:41,253] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:57:41,254] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:57:42,677] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:57:42,678] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:57:44,377] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:57:44,378] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:57:45,965] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:57:45,966] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:57:47,159] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:57:47,160] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:57:49,077] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:57:49,078] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:57:50,871] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:57:50,898] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:57:52,969] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:57:52,970] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:57:54,766] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:57:54,767] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:57:56,319] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:57:56,355] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:57:58,245] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:57:58,246] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:57:59,617] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:57:59,619] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:58:00,912] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:58:00,913] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:58:02,818] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:58:02,820] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:58:04,212] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:58:04,213] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:58:05,699] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:58:05,699] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:58:07,688] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:58:07,690] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:58:08,982] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:58:09,017] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:58:10,357] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:58:10,358] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:58:12,213] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:58:12,217] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:58:13,814] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:58:13,815] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:58:14,995] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:58:14,996] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:58:17,022] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:58:17,022] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:58:18,185] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:58:18,186] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:58:19,955] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:58:19,956] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:58:21,594] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:58:21,594] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:58:22,810] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:58:22,811] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:58:24,133] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:58:24,134] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:58:25,367] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:58:25,368] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:58:26,552] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:58:26,553] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:58:28,621] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:58:28,622] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:58:29,870] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:58:29,871] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:58:31,445] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:58:31,446] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:58:32,921] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:58:32,923] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:58:34,565] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:58:34,565] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:58:36,451] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:58:36,452] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:58:38,328] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:58:38,329] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:58:40,336] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:58:40,337] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:58:42,024] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:58:42,025] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:58:43,542] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:58:43,542] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:58:44,960] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:58:44,961] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:58:46,764] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:58:46,764] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:58:48,257] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:58:48,258] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:58:49,411] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:58:49,412] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:58:51,225] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:58:51,226] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:58:53,167] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:58:53,168] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:58:54,755] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:58:54,755] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:58:56,474] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:58:56,475] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:58:57,989] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:58:57,990] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:58:59,215] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:58:59,216] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:59:00,863] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:59:00,875] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:59:02,968] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:59:02,968] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:59:04,895] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:59:04,896] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:59:06,745] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:59:06,746] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:59:08,805] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:59:08,805] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:59:10,315] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:59:10,316] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:59:12,131] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:59:12,132] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:59:14,120] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:59:14,120] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:59:15,522] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:59:15,523] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:59:17,164] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:59:17,164] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:59:19,009] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:59:19,010] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:59:20,629] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:59:20,631] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:59:21,956] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:59:21,962] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:59:23,937] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:59:23,938] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:59:25,986] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:59:25,987] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:59:27,379] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:59:27,380] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:59:28,675] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:59:28,676] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:59:30,231] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:59:30,272] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:59:31,378] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:59:31,378] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:59:33,369] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:59:33,370] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:59:35,155] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:59:35,156] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:59:36,516] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:59:36,517] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:59:38,017] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:59:38,018] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:59:39,536] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:59:39,537] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:59:41,235] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:59:41,236] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:59:42,638] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:59:42,639] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:59:44,049] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:59:44,050] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:59:45,419] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:59:45,420] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:59:46,954] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:59:46,955] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:59:49,033] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:59:49,035] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:59:50,937] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:59:50,937] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:59:52,359] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:59:52,360] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:59:54,028] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:59:54,029] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:59:55,522] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:59:55,523] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:59:57,399] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:59:57,400] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:59:58,791] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 02:59:58,792] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
