[2019-12-09 19:01:06,029] INFO [GroupMetadataManager brokerId=0] Removed 0 expired offsets in 0 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
[2019-12-09 19:04:30,405] INFO [GroupCoordinator 0]: Member consumer-2-1ddca6f4-b13c-4cef-b7be-621d724ed8ae in group group_json has left, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2019-12-09 19:04:30,447] INFO [GroupCoordinator 0]: Preparing to rebalance group group_json in state PreparingRebalance with old generation 17 (__consumer_offsets-2) (reason: removing member consumer-2-1ddca6f4-b13c-4cef-b7be-621d724ed8ae on LeaveGroup) (kafka.coordinator.group.GroupCoordinator)
[2019-12-09 19:04:30,447] INFO [GroupCoordinator 0]: Group group_json with generation 18 is now empty (__consumer_offsets-2) (kafka.coordinator.group.GroupCoordinator)
[2019-12-09 19:11:06,029] INFO [GroupMetadataManager brokerId=0] Removed 0 expired offsets in 0 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
[2019-12-09 19:17:24,190] INFO [GroupCoordinator 0]: Preparing to rebalance group group_json in state PreparingRebalance with old generation 18 (__consumer_offsets-2) (reason: Adding new member consumer-2-e483f809-db74-41dd-9dee-23e6f7200610 with group instanceid None) (kafka.coordinator.group.GroupCoordinator)
[2019-12-09 19:17:24,235] INFO [GroupCoordinator 0]: Stabilized group group_json generation 19 (__consumer_offsets-2) (kafka.coordinator.group.GroupCoordinator)
[2019-12-09 19:17:24,240] INFO [GroupCoordinator 0]: Assignment received from leader for group group_json for generation 19 (kafka.coordinator.group.GroupCoordinator)
[2019-12-09 19:20:17,304] INFO [GroupCoordinator 0]: Member consumer-2-e483f809-db74-41dd-9dee-23e6f7200610 in group group_json has left, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2019-12-09 19:20:17,353] INFO [GroupCoordinator 0]: Preparing to rebalance group group_json in state PreparingRebalance with old generation 19 (__consumer_offsets-2) (reason: removing member consumer-2-e483f809-db74-41dd-9dee-23e6f7200610 on LeaveGroup) (kafka.coordinator.group.GroupCoordinator)
[2019-12-09 19:20:17,354] INFO [GroupCoordinator 0]: Group group_json with generation 20 is now empty (__consumer_offsets-2) (kafka.coordinator.group.GroupCoordinator)
[2019-12-09 19:20:25,146] INFO [GroupCoordinator 0]: Preparing to rebalance group group_json in state PreparingRebalance with old generation 20 (__consumer_offsets-2) (reason: Adding new member consumer-2-2c671ab4-f9a4-43df-a852-9ee4b8081c95 with group instanceid None) (kafka.coordinator.group.GroupCoordinator)
[2019-12-09 19:20:25,165] INFO [GroupCoordinator 0]: Stabilized group group_json generation 21 (__consumer_offsets-2) (kafka.coordinator.group.GroupCoordinator)
[2019-12-09 19:20:25,168] INFO [GroupCoordinator 0]: Assignment received from leader for group group_json for generation 21 (kafka.coordinator.group.GroupCoordinator)
[2019-12-09 19:21:06,029] INFO [GroupMetadataManager brokerId=0] Removed 0 expired offsets in 0 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
[2019-12-09 19:25:33,245] INFO [GroupCoordinator 0]: Member consumer-2-2c671ab4-f9a4-43df-a852-9ee4b8081c95 in group group_json has left, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2019-12-09 19:25:33,270] INFO [GroupCoordinator 0]: Preparing to rebalance group group_json in state PreparingRebalance with old generation 21 (__consumer_offsets-2) (reason: removing member consumer-2-2c671ab4-f9a4-43df-a852-9ee4b8081c95 on LeaveGroup) (kafka.coordinator.group.GroupCoordinator)
[2019-12-09 19:25:33,270] INFO [GroupCoordinator 0]: Group group_json with generation 22 is now empty (__consumer_offsets-2) (kafka.coordinator.group.GroupCoordinator)
[2019-12-09 19:25:41,936] INFO [GroupCoordinator 0]: Preparing to rebalance group group_json in state PreparingRebalance with old generation 22 (__consumer_offsets-2) (reason: Adding new member consumer-2-ca8804f7-7065-4db6-8d5e-7a3cea99f2f4 with group instanceid None) (kafka.coordinator.group.GroupCoordinator)
[2019-12-09 19:25:41,970] INFO [GroupCoordinator 0]: Stabilized group group_json generation 23 (__consumer_offsets-2) (kafka.coordinator.group.GroupCoordinator)
[2019-12-09 19:25:41,974] INFO [GroupCoordinator 0]: Assignment received from leader for group group_json for generation 23 (kafka.coordinator.group.GroupCoordinator)
[2019-12-09 19:30:29,546] INFO [GroupCoordinator 0]: Member consumer-2-ca8804f7-7065-4db6-8d5e-7a3cea99f2f4 in group group_json has left, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2019-12-09 19:30:29,554] INFO [GroupCoordinator 0]: Preparing to rebalance group group_json in state PreparingRebalance with old generation 23 (__consumer_offsets-2) (reason: removing member consumer-2-ca8804f7-7065-4db6-8d5e-7a3cea99f2f4 on LeaveGroup) (kafka.coordinator.group.GroupCoordinator)
[2019-12-09 19:30:29,555] INFO [GroupCoordinator 0]: Group group_json with generation 24 is now empty (__consumer_offsets-2) (kafka.coordinator.group.GroupCoordinator)
[2019-12-09 19:30:38,688] INFO [GroupCoordinator 0]: Preparing to rebalance group group_json in state PreparingRebalance with old generation 24 (__consumer_offsets-2) (reason: Adding new member consumer-2-1e202930-b3fa-4b9d-b5bf-c5013bfd7357 with group instanceid None) (kafka.coordinator.group.GroupCoordinator)
[2019-12-09 19:30:38,732] INFO [GroupCoordinator 0]: Stabilized group group_json generation 25 (__consumer_offsets-2) (kafka.coordinator.group.GroupCoordinator)
[2019-12-09 19:30:38,745] INFO [GroupCoordinator 0]: Assignment received from leader for group group_json for generation 25 (kafka.coordinator.group.GroupCoordinator)
[2019-12-09 19:31:06,029] INFO [GroupMetadataManager brokerId=0] Removed 0 expired offsets in 0 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
[2019-12-09 19:38:41,744] INFO [GroupCoordinator 0]: Member consumer-2-1e202930-b3fa-4b9d-b5bf-c5013bfd7357 in group group_json has left, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2019-12-09 19:38:41,798] INFO [GroupCoordinator 0]: Preparing to rebalance group group_json in state PreparingRebalance with old generation 25 (__consumer_offsets-2) (reason: removing member consumer-2-1e202930-b3fa-4b9d-b5bf-c5013bfd7357 on LeaveGroup) (kafka.coordinator.group.GroupCoordinator)
[2019-12-09 19:38:41,798] INFO [GroupCoordinator 0]: Group group_json with generation 26 is now empty (__consumer_offsets-2) (kafka.coordinator.group.GroupCoordinator)
[2019-12-09 19:38:50,928] INFO [GroupCoordinator 0]: Preparing to rebalance group group_json in state PreparingRebalance with old generation 26 (__consumer_offsets-2) (reason: Adding new member consumer-2-84b38922-3ceb-42a6-94df-551001ef58c8 with group instanceid None) (kafka.coordinator.group.GroupCoordinator)
[2019-12-09 19:38:50,930] INFO [GroupCoordinator 0]: Stabilized group group_json generation 27 (__consumer_offsets-2) (kafka.coordinator.group.GroupCoordinator)
[2019-12-09 19:38:50,933] INFO [GroupCoordinator 0]: Assignment received from leader for group group_json for generation 27 (kafka.coordinator.group.GroupCoordinator)
[2019-12-09 19:40:12,286] INFO [GroupCoordinator 0]: Member consumer-2-84b38922-3ceb-42a6-94df-551001ef58c8 in group group_json has left, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2019-12-09 19:40:12,338] INFO [GroupCoordinator 0]: Preparing to rebalance group group_json in state PreparingRebalance with old generation 27 (__consumer_offsets-2) (reason: removing member consumer-2-84b38922-3ceb-42a6-94df-551001ef58c8 on LeaveGroup) (kafka.coordinator.group.GroupCoordinator)
[2019-12-09 19:40:12,338] INFO [GroupCoordinator 0]: Group group_json with generation 28 is now empty (__consumer_offsets-2) (kafka.coordinator.group.GroupCoordinator)
[2019-12-09 19:40:19,545] INFO [GroupCoordinator 0]: Preparing to rebalance group group_json in state PreparingRebalance with old generation 28 (__consumer_offsets-2) (reason: Adding new member consumer-2-4efe78ce-b823-4201-8051-a8f6fbbf2f0f with group instanceid None) (kafka.coordinator.group.GroupCoordinator)
[2019-12-09 19:40:19,545] INFO [GroupCoordinator 0]: Stabilized group group_json generation 29 (__consumer_offsets-2) (kafka.coordinator.group.GroupCoordinator)
[2019-12-09 19:40:19,549] INFO [GroupCoordinator 0]: Assignment received from leader for group group_json for generation 29 (kafka.coordinator.group.GroupCoordinator)
[2019-12-09 19:41:06,029] INFO [GroupMetadataManager brokerId=0] Removed 0 expired offsets in 0 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
[2019-12-09 19:42:40,228] INFO Terminating process due to signal SIGHUP (org.apache.kafka.common.utils.LoggingSignalHandler)
[2019-12-09 19:42:40,265] INFO Terminating process due to signal SIGHUP (org.apache.kafka.common.utils.LoggingSignalHandler)
[2019-12-09 19:42:40,513] INFO [KafkaServer id=0] shutting down (kafka.server.KafkaServer)
[2019-12-09 19:42:40,514] INFO [KafkaServer id=0] Starting controlled shutdown (kafka.server.KafkaServer)
[2019-12-09 19:42:41,000] WARN Session 0x10006e1870c0000 for server localhost/127.0.0.1:2181, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.io.IOException: Connection reset by peer
	at java.base/sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:233)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223)
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:358)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:68)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:366)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2019-12-09 19:42:41,367] INFO [ZooKeeperClient Kafka server] Waiting until connected. (kafka.zookeeper.ZooKeeperClient)
[2019-12-09 19:42:41,368] INFO [ZooKeeperClient Kafka server] Connected. (kafka.zookeeper.ZooKeeperClient)
[2019-12-09 19:42:43,666] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-09 19:42:43,965] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-09 19:42:44,151] INFO [ZooKeeperClient Kafka server] Waiting until connected. (kafka.zookeeper.ZooKeeperClient)
[2019-12-09 19:42:45,277] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-09 19:42:45,277] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-09 19:42:46,511] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-09 19:42:46,513] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-09 19:42:48,126] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-09 19:42:48,158] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-09 19:42:49,501] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-09 19:42:49,502] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-09 19:42:51,198] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-09 19:42:51,199] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-09 19:42:53,195] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-09 19:42:53,205] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-09 19:42:54,872] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-09 19:42:54,872] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-09 19:42:56,243] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-09 19:42:56,244] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-09 19:42:57,905] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-09 19:42:58,036] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-09 19:42:59,383] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-09 19:43:00,180] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-09 19:43:01,786] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-09 19:43:01,787] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-09 19:43:03,578] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-09 19:43:03,579] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-09 19:43:05,101] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-09 19:43:05,101] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-09 19:43:06,340] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-09 19:43:06,340] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-09 19:43:07,961] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-09 19:43:07,961] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-09 19:43:09,649] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-09 19:43:09,649] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-09 19:43:11,391] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-09 19:43:11,392] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-09 19:43:13,316] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-09 19:43:13,317] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-09 19:43:14,728] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-09 19:43:14,728] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-09 19:43:16,754] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-09 19:43:16,754] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-09 19:43:18,130] INFO [GroupCoordinator 0]: Member consumer-2-4efe78ce-b823-4201-8051-a8f6fbbf2f0f in group group_json has left, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2019-12-09 19:43:18,130] INFO [GroupCoordinator 0]: Preparing to rebalance group group_json in state PreparingRebalance with old generation 29 (__consumer_offsets-2) (reason: removing member consumer-2-4efe78ce-b823-4201-8051-a8f6fbbf2f0f on LeaveGroup) (kafka.coordinator.group.GroupCoordinator)
[2019-12-09 19:43:18,130] INFO [GroupCoordinator 0]: Group group_json with generation 30 is now empty (__consumer_offsets-2) (kafka.coordinator.group.GroupCoordinator)
[2019-12-09 19:43:18,183] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-09 19:43:18,184] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-09 19:43:19,305] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-09 19:43:19,306] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-09 19:43:20,575] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-09 19:43:20,576] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-09 19:43:21,870] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-09 19:43:21,871] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-09 19:43:23,066] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-09 19:43:23,066] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-09 19:43:24,318] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-09 19:43:24,318] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-09 19:43:25,884] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-09 19:43:25,884] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-09 19:43:27,312] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-09 19:43:27,312] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-09 19:43:29,173] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-09 19:43:29,173] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-09 19:43:30,284] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-09 19:43:30,285] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-09 19:43:31,650] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-09 19:43:31,651] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-09 19:43:33,465] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-09 19:43:33,466] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-09 19:43:35,431] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-09 19:43:35,866] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
